### ISSUE TITLE
Setup ESLint and Prettier

### ISSUE THREAD

**Issue by mazipan** [mazipan/buku-saku-pramuka#14]
This is my favourite setup for ESlint and Prettier: https://github.com/mazipan/vue-currency-filter

Need to change the Vue part into the React.

**Comment by mazipan** [comment]
Related to PR #13

**Comment by StellaJung-Student** [comment]
Can I take this task? Then please assign to me.

**Comment by StellaJung-Student** [comment]
@mazipan I have made PR for the issue, [here](https://github.com/mazipan/buku-saku-pramuka/pull/17).
Please review and let me know if I am wrong.
