### ISSUE TITLE
Setup Husky and Lint-Staged

### ISSUE THREAD

**Issue by mazipan** [mazipan/buku-saku-pramuka#15]
You can peek my favourite setup here: https://github.com/mazipan/vue-currency-filter

**Comment by mazipan** [comment]
Related with #14

**Comment by StellaJung-Student** [comment]
Can I take this task? Then please assign to me.

**Comment by StellaJung-Student** [comment]
@mazipan I have made PR for the issue, [here](https://github.com/mazipan/buku-saku-pramuka/pull/17).
Please review and let me know if I am wrong.
