### ISSUE TITLE
Add lesson about "sandi radio"

### ISSUE THREAD

**Issue by muhsatrio** [mazipan/buku-saku-pramuka#2]
I would like to give recommendation to add lesson about sandi radio, because it's mainly used in scout

Thank you

**Comment by mazipan** [comment]
So you have any data source for this?

**Comment by muhsatrio** [comment]
Maybe this resource wikipedia can be used

https://id.m.wikipedia.org/wiki/Alfabet_fonetik_NATO#:~:text=Berikut%20adalah%2026%20kode%20dalam,-ray%2C%20Yankee%2C%20Zulu.

**Comment by mazipan** [comment]
Yang ini ya?
Kolom "telephony"?

![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/FAA_Phonetic_and_Morse_Chart2.svg/550px-FAA_Phonetic_and_Morse_Chart2.svg.png)

**Comment by muhsatrio** [comment]
betul mas! yang dari alfa sampai zulu untuk huruf itu

**Comment by mazipan** [comment]
Thanks infonya mas @muhsatrio 
Apa mau bantuin koding juga :-D ?

**Comment by muhsatrio** [comment]
Wah boleh banget mas hehehehehehe tapi masih belum begitu lancar nextjs nih. Tapi kalo develop react sendiri sebelumnya udah pernah sih...

**Comment by mazipan** [comment]
Ditilik dulu aja, harusnya sih cuma mapping data dari table tersebut ke .js habis itu bikin UI sesuka hati.
Gak susah kok.

**Comment by muhsatrio** [comment]
Siaap mas aku coba mulai kerjain yah

**Comment by mazipan** [comment]
Terima kasih atas kontribusinya, jangan bosan 😂

**Comment by raisoturu** [comment]
Halo mas @mazipan, izin buat nambahin audio menggunakan [Web Speech API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API) supaya tau pronouncenya.

**Comment by mazipan** [comment]
Open issue dulu mas @raisoturu abis itu open PR kasih referensi ke nomor issue nya

**Comment by muhsatrio** [comment]
Mas @mazipan, ada miss sedikit nih. Untuk button `Selanjutnya` di page `Kode Morse` lupa ditambahin ke halaman `Kode Radio`
