### ISSUE TITLE
Add "Hari Peringatan Nasional"

### ISSUE THREAD

**Issue by omawang** [mazipan/buku-saku-pramuka#22]
I have looked at this [image](https://cf.shopee.co.id/file/e9cb1e2714655e39b14db6936dbdffb8) about "Daftar Isi - Buku Saku Pramuka". There is "Hari Peringatan Nasional" at there. So i think, it'll be good if it can be at this repo too. I would like to add it.

reference: https://id.wikipedia.org/wiki/Daftar_hari_penting_di_Indonesia

**Comment by mazipan** [comment]
Do you want to work on this issue @omawang ?
