### ISSUE TITLE
Konten - Lagu-Lagu Pramuka

### ISSUE THREAD

**Issue by mazipan** [mazipan/buku-saku-pramuka#25]
Berisi kumpulan lagu-lagu umum yang seringkali dinyanyikan pada saat kegiatan Pramuka.

Paling tidak memiliki:
- Lirik
- Audio MP3 atau YouTube Link

**Comment by mazipan** [comment]
Referensi: https://www.pramukaindonesia.com/2015/07/download-kumpulan-lagu-lagu-pramuka.html?m=1

**Comment by arispati** [comment]
saya akan coba mengerjakan issue ini kak
