### ISSUE TITLE
Konten - Kwartir di Indonesia

### ISSUE THREAD

**Issue by mazipan** [mazipan/buku-saku-pramuka#26]
Referensi: https://id.m.wikipedia.org/wiki/Gerakan_Pramuka_Indonesia

**Comment by ifdion** [comment]
@mazipan Ini maksudnya buat konten baru untuk webapp nya ya mas? Boleh saya coba?

**Comment by mazipan** [comment]
Iya, bikin halaman baru, dan mapping data dari website ke file `.js`
