### ISSUE TITLE
Konten - Sandi Ambalan

### ISSUE THREAD

**Issue by mazipan** [mazipan/buku-saku-pramuka#28]
Referensi: https://www.pramukaindonesia.com/2014/10/sandi-ambalan-bhinneka-tunggal-ika.html?m=1

**Comment by roniardynt** [comment]
Saya izin mengerjakan bagian ini mas

**Comment by raisoturu** [comment]
Eh mas, bukannya tiap ambalan sandinya beda2 ya?

**Comment by mazipan** [comment]
Ada referensi gak ya mas @raisoturu?
Saat ini saya baru menemukan web di atas aja sih.

**Comment by raisoturu** [comment]
Ini ada contoh dari ambalan ksatria garuda
https://ksatriagaruda.wordpress.com/sandi-dan-amsal-ambalan-ksatria-garuda-07051-07052/

Ini dari ambalan lain
http://panduempati43.blogspot.com/2013/10/sandi-ambalan.html#:~:text=Sandi%20Ambalan%20yaitu%20karangan%20atau,atau%20pandega%20di%20ambalan%2F%20racana.

Dari Ambalan saya isinya beda lagi (Adatnya gaboleh dishare :))) ).
Menurut saya buat konten buku saku kurang cocok deh, soalnya emang isinya beda2 dan masing2 ambalan punya adatnya masing2.

**Comment by mazipan** [comment]
Termasuk sandi Ambalan yang bhinneka tunggal Ika di atas ya mas?

**Comment by raisoturu** [comment]
Iya mas

**Comment by mazipan** [comment]
Then we should take out the page.
Can you @roniardynt or @raisoturu help on this?

**Comment by arispati** [comment]
I can take this @mazipan
