### ISSUE TITLE
SEO - generate sitemap.xml

### ISSUE THREAD

**Issue by mazipan** [mazipan/buku-saku-pramuka#37]
Generate the sitemap.xml for submit in search console

**Comment by mlutfib** [comment]
@mazipan i want to try solve this issue, may i mas?

**Comment by mazipan** [comment]
Sikat mas @mlutfib

**Comment by mlutfib** [comment]
halo mas @mazipan ini harus dari `daftar-isi.js`  karena saya kesulitan import file ES6 ke script commonJS, atau boleh sitemap berdasarkan modul di folder pages?

Thanks Before

**Comment by mazipan** [comment]
Read dir aja dari folder `pages`.
Pake `fs`
