### ISSUE TITLE
Mistypography for "UUD 1945"

### ISSUE THREAD

**Issue by muhsatrio** [mazipan/buku-saku-pramuka#4]
![Screenshot from 2020-10-01 23-45-49](https://user-images.githubusercontent.com/11547086/94839133-cab1cc80-0440-11eb-80e1-4542b135277e.png)
For this, I think it would be better as `Pembukaan UUD 1945` rather than `UUD 1945`. Because `UUD 1945` has the meaning not only the opening of UUD 1945 but also contains the clauses of it.

@mazipan

**Comment by mazipan** [comment]
Nice catch 👋

**Comment by muhsatrio** [comment]
Kindly check #5 ehehehehehe
