### ISSUE TITLE
Bug - Warning error when load the home page for the first time

### ISSUE THREAD

**Issue by arispati** [mazipan/buku-saku-pramuka#60]
**Describe the bug**
When load the home page for the first time, warning error appear in the console

**To Reproduce**
1. Pull the latest commit from master branch
2. Run `npm run dev`
3. Open `http://localhost:3000` on the browser
4. See error in the console

**Expected behavior**
Warning errors should not appear

**Screenshots**
![image](https://user-images.githubusercontent.com/13604647/96355765-a841d380-110f-11eb-8392-c43efb6c4e0e.png)

**Comment by mazipan** [comment]
Can you help on this @arispati ?

**Comment by arispati** [comment]
I'll try it @mazipan , I'll also fix some wrong word and layout then. 🚀
