### ISSUE TITLE
Bug - Dark Mode Have a Blink when Hard Reload

### ISSUE THREAD

**Issue by mazipan** [mazipan/buku-saku-pramuka#66]
**Describe the bug**

When you're on the dark mode and refresh the page, you will see the light mode first then it swap to dark mode.

**Expected behavior**

Smooth interaction when reload page

**Comment by oli799** [comment]
Hello @mazipan , I would  work on it if you assign me :)

**Comment by mazipan** [comment]
https://hangindev.com/blog/avoid-flash-of-default-theme-an-implementation-of-dark-mode-in-react-app

**Comment by raisoturu** [comment]
https://fatihkalifa.com/dark-mode-web#flashof%20default%20theme%20(fodt)
