### ISSUE TITLE
Bug - Dark mode didn't change the theme meta tag

### ISSUE THREAD

**Issue by mazipan** [mazipan/buku-saku-pramuka#67]
**Describe the bug**

When you're on the dark mode, you will see a different theme in the meta tag

**Expected behavior**

Should align the theme meta tag with the header color

**Screenshots**

![Screenshot_20201018-181733_Chrome](https://user-images.githubusercontent.com/7221389/96365927-63995500-116e-11eb-80c4-7102b4c9dd72.jpg)

**Comment by sprakash57** [comment]
May i take this up?

**Comment by sprakash57** [comment]
I have raise PR [https://github.com/mazipan/buku-saku-pramuka/pull/69](https://github.com/mazipan/buku-saku-pramuka/pull/69). Please review. Thank you!!
